salario=float(input('Salário:R$ '))
ir=salario-(salario*(11/100))
ir_desc=salario*(11/100)
inss=salario-(salario*(8/100))
inss_desc=salario*(8/100)
sindicato=salario-(salario*(5/100))
sind_desc=salario*(5/100)
liquido=salario-(ir_desc+inss_desc+sind_desc)

print('Salário bruto:R$ {}'.format(salario))
print('Imposto de renda:R$ {:.2f}'.format(ir))
print('INSS:R$ {:.2f}'.format(inss))
print('Sindicato:R$ {:.2f}'.format(sindicato))
print('Salário liquido:R$ {:.2f}'.format(liquido))
